// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-FPkpxI-17xwYuZFopyhL2EIB59yZs4',
    appId: '1:364902792906:web:8e790158a1752db2873e33',
    messagingSenderId: '364902792906',
    projectId: 'shilaf-313d3',
    authDomain: 'shilaf-313d3.firebaseapp.com',
    storageBucket: 'shilaf-313d3.firebasestorage.app',
    measurementId: 'G-QV7J21C95L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhoy37Ed--UzwYkpyCyw4FP0wqk5_zy3U',
    appId: '1:364902792906:android:ce19a767a3bd17cc873e33',
    messagingSenderId: '364902792906',
    projectId: 'shilaf-313d3',
    storageBucket: 'shilaf-313d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXhVoSvOG_1PQRVOa_McXH8Ak9PjpBE8',
    appId: '1:364902792906:ios:7618efdf55821394873e33',
    messagingSenderId: '364902792906',
    projectId: 'shilaf-313d3',
    storageBucket: 'shilaf-313d3.firebasestorage.app',
    iosBundleId: 'com.example.shilaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXhVoSvOG_1PQRVOa_McXH8Ak9PjpBE8',
    appId: '1:364902792906:ios:7618efdf55821394873e33',
    messagingSenderId: '364902792906',
    projectId: 'shilaf-313d3',
    storageBucket: 'shilaf-313d3.firebasestorage.app',
    iosBundleId: 'com.example.shilaf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT-FPkpxI-17xwYuZFopyhL2EIB59yZs4',
    appId: '1:364902792906:web:3d27b8e86a5995de873e33',
    messagingSenderId: '364902792906',
    projectId: 'shilaf-313d3',
    authDomain: 'shilaf-313d3.firebaseapp.com',
    storageBucket: 'shilaf-313d3.firebasestorage.app',
    measurementId: 'G-29W20RKBMH',
  );
}
